export type {
  Product,
  ProductCategory,
  ProductDimensions,
  ProductImage,
  ProductMedia,
  ProductOption,
  ProductOptionValue,
  ProductStatus,
  ProductGenerationStatus,
  AIProductAnalysis,
  AIProductAnalysisRequest,
  AIProductAnalysisResponse,
  AIProductDraft,
  AIDetectedOption,
} from "./types/catalog.types";